### ISSUE TITLE
Is it possible to patch the font easily?

### ISSUE THREAD

**Issue by mainrs** [IdreesInc/Monocraft#1]
I do not have much FontForge experience. But say I want to make the difference between `(` and `{` more visible. Is there an easy way to do this without having to manually adjust the character each time you update the font?

**Comment by IdreesInc** [comment]
Braces have now been updated! Check out the releases tab to download the newest version.
As for patching the font, unfortunately the only way to do so is to modify the FontForge file and submit a PR.
