### ISSUE TITLE
non-ligature version

### ISSUE THREAD

**Issue by coffincw** [IdreesInc/Monocraft#10]
Would it be possible to add a download to a version without the ligatures?

**Comment by ChiefArug** [comment]
Most applications that support ligatures also support turning them off

**Comment by ignaloidas** [comment]
Programing specific ligatures are bad https://practicaltypography.com/ligatures-in-programming-fonts-hell-no.html

While there are no other ligatures in this font, in other fonts I can't get ligatures that actually help me if I want to disable ligatures that impede me.

**Comment by cdrfun** [comment]
VisualStudio doesnt support turning them off. afaik

**Comment by Svintooo** [comment]
Having ligatures like these being triggered in regular expressions (or other kind of strings) can be quite annoying.
If this happens while reading someone else s code, then you can not just reorder the characters to fix the problem.

If you feel like making a non-ligature version I would be very grateful.

**Comment by Xaeroxe** [comment]
Yeah many applications don't support disabling these. I'd download a zero ligatures version.

**Comment by NoSkillPureAndy** [comment]
I agree. I do not like ligatures one bit.

**Comment by nick21500** [comment]
@IdreesInc pls pls I'd love to use this font :)

**Comment by mrparn** [comment]
I just want to add my voice, please make a non-ligature version. I don't think it's a good practice to make ligatures that look like different, also valid characters, but if you are not bothered by them, more power to you.

**Comment by inqueblot** [comment]
Please this.

**Comment by teafoot** [comment]
yes pls

**Comment by kiwec** [comment]
STOP COMMENTING +1 FFS

YOU'RE SHITTING UP MY NOTIFICATIONS

**Comment by teafoot** [comment]
+1 suk it @kiwec

**Comment by Xaeroxe** [comment]
It might be a good idea to lock this. I’m not sure any more productive conversation can be had unless it’s @IdreesInc saying something.

**Comment by keupoz** [comment]
Here's a version with ligatures removed using opentype.js library
[Monocraft Unligatured.zip](https://github.com/IdreesInc/Monocraft/files/9543195/Monocraft.Unligatured.zip)

**Comment by Xaeroxe** [comment]
@keupoz The font you posted doesn't render at all for me. System is Windows 11

**Comment by keupoz** [comment]
> @keupoz The font you posted doesn't render at all for me. System is Windows 11

oops, yeah, I see it's broken, need to investigate more how to properly remove ligatures

**Comment by keupoz** [comment]
@Xaeroxe never worked with fonts before, I also renamed the font to "Monocraft Unligatured" just in case and looks like one of name fields can't have spaces. This one should work
[Monocraft Unligatured.zip](https://github.com/IdreesInc/Monocraft/files/9546411/Monocraft.Unligatured.zip)

**Comment by Xaeroxe** [comment]
@keupoz same problem
![image](https://user-images.githubusercontent.com/6182002/190003794-58e9f421-1281-4f07-906d-1320c8227c49.png)

**Comment by keupoz** [comment]
@Xaeroxe idk then :( Maybe deleting ligatures manually with Font Forge may help because looks like the font was made in that program

**Comment by Seele0oO** [comment]
yes,It's a important thing.

**Comment by IdreesInc** [comment]
Ligature free version will be released as part of v2.1, which I will make available sometime tonight after finishing up with a few other issues!

I can't believe that somehow programming with the _Minecraft_ font is fine, but adding ligatures is just one step too far...
