### ISSUE TITLE
Cyrillic `ц` renders higher than it should.

### ISSUE THREAD

**Issue by btvoidx** [IdreesInc/Monocraft#106]
**Describe the bug**
Cyrillic symbol `ц` (lowercase) symbol renders quite a bit higher than it should. `Ц` (uppercase) looks just fine to me. I use `.otf` version, but every other appears to also have the mistake.

**Expected behaviour**
It should be in line with all other letters.

**Screenshots**
Font install window
![image](https://user-images.githubusercontent.com/37330718/217065913-ea5f0dda-e666-45e0-b72f-a186c56f8125.png)

In windows terminal
![image](https://user-images.githubusercontent.com/37330718/217065753-94b815d9-6e36-4f82-b494-d566d0ae385a.png)

**Operating system**
Windows

**Software**
Windows font install window, so every software I suppose.

**Additional context**
I believe it was fine just a few versions ago.

**Comment by IdreesInc** [comment]
Hm, looks like this is actually an oversight on my part where I never added a descent to the lowercase version of "ц". Will fix in the next version and comment here when it is released. Thanks for bringing this to my attention!

**Comment by IdreesInc** [comment]
Fixed as part of v2.5, thank you for your patience!
