### ISSUE TITLE
Shorten periods?

### ISSUE THREAD

**Issue by catches** [IdreesInc/Monocraft#118]
If I have something like this with periods
![image](https://user-images.githubusercontent.com/105005455/224797426-07ae44a4-a16b-4abe-b130-48c6d00bd0a9.png)
![image](https://user-images.githubusercontent.com/105005455/224797719-8cffbbcc-997f-4471-b069-c3bbd5e092a8.png)
it stretches it out and puts spaces between them, is it possible to just remove the spaces, and align them properly?

**Comment by Ciubix8513** [comment]
I think this works as it should, it's a monospace font, meaning all characters have the same width.

Here's a non monospace minecraft font: https://github.com/IdreesInc/Minecraft-Font
