### ISSUE TITLE
HTML comment ligature

### ISSUE THREAD

**Issue by Tharmin** [IdreesInc/Monocraft#129]
Hi, I would like to request a ligature for the HTML comment syntax, `<!-- comment -->`
With the new extended ligatures, only the `-->` at the end of the comment is changed, as in the example below:
![image](https://github.com/IdreesInc/Monocraft/assets/91003689/c6d55bf2-e709-4ad5-b887-4cede4844e05)

In this case, perhaps when the characters for `<!--` are detected, the two hyphens could be merged into one solid line? If there are any better solutions though, please do feel free to implement what you feel is appropriate in this situation, thanks!

**Comment by Ciubix8513** [comment]
I gave it a try
![image](https://github.com/IdreesInc/Monocraft/assets/57328501/88e9c072-18a2-4200-8ec5-0a5e075f4558)
