### ISSUE TITLE
Provide NerdFont version

### ISSUE THREAD

**Issue by Supersebi3** [IdreesInc/Monocraft#13]
I realize I can just patch the font myself, but it would be convenient and make the font a lot more usable to provide a version that supports NerdFont characters. Maybe some of them could even be adjusted to fit the pixelated style?

**Comment by GeorgeBroughton** [comment]
ikr? imagine using this for PowerShell using OhMyPosh or something

**Comment by mainrs** [comment]
For the time being, the font can be patched by everybody: `nerd-font-patcher Monocraft.otf --complete --careful --outputdir $outdir`

**Comment by ArtistCalled** [comment]
Yes

**Comment by pseudoparenchymatous** [comment]
Can someone share their patched nerdfont for this? I can't patch cause I only use Termux on android 😭. Please, thanks 🥺

**Comment by IdreesInc** [comment]
Now that Monocraft is generated via a script, I am revisiting this as an option.

**Comment by IdreesInc** [comment]
Will release a version patched with the font-patcher in version 2.1 later tonight

**Comment by kurokirasama** [comment]
cool!

**Comment by braveltd** [comment]
but provide plz nerd font version! it's easy!

i'm gonna patch it myself, but we need a nerd font version!!

**Comment by braveltd** [comment]
Already closed! Monocraft nerd font is here baby!!
