### ISSUE TITLE
Icons 

### ISSUE THREAD

**Issue by abdlmutii** [IdreesInc/Monocraft#132]
**What feature would you like added to Monocraft?**
*Note that if you would like to request additional characters/glyphs/ligatures to be added, please use the "Additional Glyphs Request" template instead*

Add icons, like nerd fonts

**Comment by Ciubix8513** [comment]
I don't think this is really possible, a lot of the nerd fonts symbols are very detailed and wouldn't translate well.
But even if some symbols are added I think the style clash of a partial font may be worse than just having no monocraft characters for them. 

But there's no technical limitation on that, at least i don't think there should be one, so give it a try if you want, adding a new glyph is as easy as editing a bit of json
