### ISSUE TITLE
Question: which release asset should i use in VS Code on macOS?

### ISSUE THREAD

**Issue by zhangkai803** [IdreesInc/Monocraft#135]
What's the difference between `Monocraft.ttf` and `Monocraft-nerd-fonts-patched.ttf`?

**Comment by Ciubix8513** [comment]
`Monocraft-nerd-fonts-patched.ttf` contains  [nerdfonts](https://www.nerdfonts.com/), a collection of various tech/programming symbols, like for example , langauge logos. They're used for various  TUI stuff and don't really matter inside a graphical editor like vscode. 

However it doesn't really cost anything to have them, so i'd say it's better to use `Monocraft-nerd-fonts-patched.ttf`

**Comment by zhangkai803** [comment]
> `Monocraft-nerd-fonts-patched.ttf` contains  [nerdfonts](https://www.nerdfonts.com/), a collection of various tech/programming symbols, like for example , langauge logos. They're used for various  TUI stuff and don't really matter inside a graphical editor like vscode. 
> 
> 
> 
> However it doesn't really cost anything to have them, so i'd say it's better to use `Monocraft-nerd-fonts-patched.ttf`

Thanks. 😄
