### ISSUE TITLE
Provide "pure" version of font

### ISSUE THREAD

**Issue by ixnoahlive** [IdreesInc/Monocraft#140]
Currently, the Monocraft font is one of the only Minecraft fonts with tons of ligatures and glyphs from the 1.13 Font Update. This is great, but unfortunately the mono typeface for latin symbols (ABCXYZ) holds it back a bit for general use on things like websites. I think a pure version of the font that is just the monocraft font with the changes from MC7 (default mc font) reverted could be a great help and would hopefully not be *too* much work as many rips of MC7 exist already.

**Comment by IdreesInc** [comment]
You might prefer this, which was what I first created before making Monocraft: https://github.com/IdreesInc/Minecraft-Font
While I don't intend to update that project any more, someone might make a fork in the future with additional glyphs added. Sorry that I can't help further!
