### ISSUE TITLE
"ц" in Cyrillic

### ISSUE THREAD

**Issue by omores** [IdreesInc/Monocraft#142]
**Describe the bug**
The letter "ц" in the Cyrillic alphabet is higher than the others and looks wrong

**Expected behavior**
the height of the letter “ц” must match the other letters in the Cyrillic alphabet

**Screenshots**
![fontview_sR3ZcHNfdE](https://github.com/IdreesInc/Monocraft/assets/124463839/54827124-efca-4b1c-b45d-433beabade84)
![fontview_DzpdYDR0W7](https://github.com/IdreesInc/Monocraft/assets/124463839/fa1bc26c-1b5d-484a-a479-79c0bb285d28)

**Operating system**
windows 10

**Software**
any

**Comment by Ciubix8513** [comment]
What version are you using? I don't have that issue

**Comment by omores** [comment]
Monocraft nerd fonts patched

**Comment by envyvox** [comment]
Same issue for me

**Comment by Coca162** [comment]
It seems like the Monocraft nerd fonts patched version hasn't been updated for version 3.0, it has the same hash as previous versions!

**Comment by IdreesInc** [comment]
Likely fixed as of https://github.com/IdreesInc/Monocraft/releases/tag/v4.0 , but feel free to reopen if this isn't the case!
