### ISSUE TITLE
Nerd font's have not been updated for current releases

### ISSUE THREAD

**Issue by Coca162** [IdreesInc/Monocraft#146]
Since 2.2, the sha256 hash for the nerd fonts build has remained at `QxMp8UwcRjWySNHWoNeX2sX9teZ4+tCFj+DG41azsXw=` and so hasn't been updated with any of changes in newer releases.

This being fixed would fix #142

**Comment by Coca162** [comment]
This can be seen visually as well in Plasma's font manager:
![image](https://github.com/IdreesInc/Monocraft/assets/62479942/307948b9-dc0c-4212-a1c2-6055580cd484)
3.0 Nerd Font, gaps in font should've been fixed along with ц being too high

![image](https://github.com/IdreesInc/Monocraft/assets/62479942/6cb1995d-155e-41fe-a59d-b104e8f9f04e)
Regular 3.0

**Comment by Luis-Marins** [comment]
same problem here, contains a serration in the middle of the font
![Captura de tela de 2024-06-11 10-32-41](https://github.com/IdreesInc/Monocraft/assets/155187227/c53b1d9d-0265-4328-9924-0d0c3e8ece57)

**Comment by IdreesInc** [comment]
Fixed as of [v4.0](https://github.com/IdreesInc/Monocraft/releases/tag/v4.0)
