### ISSUE TITLE
Monocraft Regular v3 + Medium(500)+Bold(600)+ExtraBold(800)+Black(900) Download

### ISSUE THREAD

**Issue by Llacoste2000** [IdreesInc/Monocraft#147]
Hello!

This isn't an issue, but rather a temporary solution for those seeking bolder styles for this font. Here's the situation: On Windows, VSCode automatically creates a bold effect when the weight exceeds 400, but this doesn't happen on MacOS.

Because I adore this font too much to wait for additional styles, I've crafted some for your use!
[Monocraft-With-Weights.zip](https://github.com/user-attachments/files/15829462/Monocraft-With-Weights.zip)

In creating these new styles, I aimed to adhere as closely as possible to the "standards." Here are the fonts and their corresponding weights:
Monocraft.ttf (400)
Monocraft-Medium.ttf (500)
Monocraft-Bold.ttf (600)
**(I omitted the 700 weight due to a visual glitch)**
Monocraft-ExtraBold.ttf (800)
Monocraft-Black.ttf (900)

Many thanks for this wonderful font!

**Comment by IdreesInc** [comment]
Brilliant job! Will look into it in a couple of weeks, currently getting married lol

**Comment by Llacoste2000** [comment]
I wish you a happy wedding then! And thanks ;)

**Comment by Dheatly23** [comment]
Just in case, did you generate the files using my PR?

**Comment by Llacoste2000** [comment]
Nope, I created them using FontLab 7 (just noticed your PR, very cool that it's coming soon then!)

**Comment by IdreesInc** [comment]
Working on getting @Dheatly23's PR reviewed rn, only a year late 😅...
Thanks @Llacoste2000 for making this, I'm sure it's helped a lot of people in the meantime!

**Comment by IdreesInc** [comment]
@Dheatly23's code has now been merged in, programmatic weights are available here: https://github.com/IdreesInc/Monocraft/releases/tag/v4.0
Thanks again, closing this now!
