### ISSUE TITLE
Turkish letters

### ISSUE THREAD

**Issue by evrifaessa** [IdreesInc/Monocraft#15]
Hey, great project!

I'd love to contribute if I could, but here's my feature request. We have some letters in the Turkish alphabet that are not included in this project. I would love to use your font if you can add these letters. Thank you.

https://en.wikipedia.org/wiki/Turkish_alphabet#Letters

**Comment by evrifaessa** [comment]
I'll try my best to contribute. I'll install FontForge but It's my first time editing a font. Let's see how it goes.

**Comment by burakowski** [comment]
For those who looks for Turkish letters in Monocraft can check MonocraftTur fork. It has been edited faithfully to Minecraft's original font family. @evrifaessa

**Comment by evrifaessa** [comment]
> For those who looks for Turkish letters in Monocraft can check MonocraftTur fork. It has been edited faithfully to Minecraft's original font family. @evrifaessa

Can you upstream it?

**Comment by burakowski** [comment]
> > For those who looks for Turkish letters in Monocraft can check MonocraftTur fork. It has been edited faithfully to Minecraft's original font family. @evrifaessa
> 
> Can you upstream it?

It's upstreamed.

**Comment by IdreesInc** [comment]
#80 should have included the remaining characters required for Turkish, but let me know if anything is missing! The font will be updated with release v2.1 which will happen sometime tonight once I finish up a few more PRs
