### ISSUE TITLE
Creeper face in the capital A

### ISSUE THREAD

**Issue by khatiba** [IdreesInc/Monocraft#18]
Are there enough pixels to make a creeper face in the capital `A` letter (or is that only the A in the logo)? It would just be a fun touch, great font though!

**Comment by IdreesInc** [comment]
Unfortunately there are not enough pixels in the letter A for that (plus that'd be different from the original font), but I definitely plan on adding a creeper face character as part of https://github.com/IdreesInc/Monocraft/issues/75. I'm thinking of either replacing 💣 or 💥 with it
