### ISSUE TITLE
Monofont Light for smaller font sizes (<12)

### ISSUE THREAD

**Issue by PoisonDarterz** [IdreesInc/Monocraft#21]
The font is a little boldish for smaller font sizes. Suggest for a lighter weighted version of the font to be made if the dev team has the extra time. 

Of course, thanks a lot for this font too!

**Comment by MauritsWilke** [comment]
+ 1, I use font size 12 as well and its a tad too bold

**Comment by IdreesInc** [comment]
Should be fixed with the new release that includes multiple font weights!
