### ISSUE TITLE
What is this theme?

### ISSUE THREAD

**Issue by CoolLoong** [IdreesInc/Monocraft#23]
![image](https://user-images.githubusercontent.com/69153398/189010091-9ee90cca-ff5c-4fc1-aa7a-c82815e06a68.png)

**Comment by rootEnginear** [comment]
I think it's Monokai Pro (https://monokai.pro/)

**Comment by CoolLoong** [comment]
> 我认为是 Monokai Pro ( https://monokai.pro/ )
thx
