### ISSUE TITLE
Add Mac installation via Homebrew

### ISSUE THREAD

**Issue by Fryguy** [IdreesInc/Monocraft#3]
I would love to be able to install this via Homebrew on Mac, so this is an enhancement request.

Homebrew has a specific way to install fonts, which makes it simple for Mac users.  See https://github.com/Homebrew/homebrew-cask-fonts

**Comment by ppwfx** [comment]
is there a benefit to using homebrew to install fonts?

**Comment by Chew** [comment]
Easier to install updates is the main thing.

**Comment by andypiper** [comment]
My immediate reaction when I learned about Monocraft was to look for it in Homebrew as well, but based on the cask-fonts contribution guidelines I am not sure it "qualifies" for that repository 😞

**Comment by Avakining** [comment]
> based on the cask-fonts contribution guidelines I am not sure it "qualifies" for that repository 😞

It could be possible to require users to tap this repo to use homebrew instead. That way, you get the easier updates without needing approval from the brew team

**Comment by andypiper** [comment]
… well, it’s in homebrew now…

**Comment by IdreesInc** [comment]
> … well, [it’s in homebrew](https://github.com/Homebrew/homebrew-cask-fonts/commit/64b4c3fcca27e8b91067da461e1303077d16579d) now…

Interesting, I plan on looking through the issues on this repo sometime this weekend but for now is this something you believe is cause for concern? You mentioned earlier it might not qualify under the homebrew font guidelines.

**Comment by Chew** [comment]
It got merged, so I suppose it's fine.

**Comment by andypiper** [comment]
I didn’t expect it to qualify, but I guess I was wrong about that… Seems like this can be closed!

**Comment by IdreesInc** [comment]
## Remaining work

- [ ] Update documentation to include homebrew installation instructions
