### ISSUE TITLE
Version for inclusion in Minecraft resource pack

### ISSUE THREAD

**Issue by DarkArc** [IdreesInc/Monocraft#30]
I'm actually curious, is there a way to use this in the actual game itself as part of a resource pack (to get a monospace font in game)?

I've always wanted the in game font to be monospace (for various commands/generating tabular data in chat)... I've "generated" some fonts but they've never ended up quite right.

**Comment by hydino2085143** [comment]
Minecraft fonts are just images, while this font is a fully fledged otf/ttf file. The two formats are not compatible, so you can't use this in a resource pack.

**Comment by DarkArc** [comment]
> Minecraft fonts are just images, while this font is a fully fledged otf/ttf file. The two formats are not compatible, so you can't use this in a resource pack. 

I realize it can't be used as is.

The author has an image similar to what Minecraft used to use. Though I'm not sure how the glyphs are processed by Minecraft exactly.

Also the game does technically support ttf, it's just not "official" support IIRC as the implementation was never finished.

**Comment by hydino2085143** [comment]
A cursory google search showed me some outdated mods which let you use TTF files into minecraft, but aside from that I couldn't find much else. If you somehow have the patience to turn the font into a minecraft font image then you'll have earned my respect! 😆

**Comment by Rippanda12** [comment]
> A cursory google search showed me some outdated mods which let you use TTF files into minecraft, but aside from that I couldn't find much else. If you somehow have the patience to turn the font into a minecraft font image then you'll have earned my respect! laughing

Theres ALOT of mods that let you do that and ubuntu mono looks great in minecraft btw

**Comment by Rippanda12** [comment]
https://www.reddit.com/r/Minecraft/comments/8yjroi/how_to_add_a_ttf_font_to_your_resource_pack/

**Comment by DarkArc** [comment]
@IdreesInc I see this was closed as completed, but where?

**Comment by IdreesInc** [comment]
Apologies, I should've added context. At this point, I don't intend to add a separate version of Monocraft just for resource packs other than the `.ttf` version included in the release. You are welcome to use programs that make it possible to add .ttf fonts. I'm sorry I can't be of more help.
