### ISSUE TITLE
-> ligature is broken in intellij

### ISSUE THREAD

**Issue by FelixStumvoll** [IdreesInc/Monocraft#31]
![image](https://user-images.githubusercontent.com/22666794/189299734-6f08cab9-1207-4fec-8b87-eb1ef2a6e0dc.png)

as seen in the screenshot the `->` ligature is not displayed correctly in intellij.
Could this be an issue with the font or a bug in intellij?

**Comment by proteck** [comment]
I have not this probleme with intelliJ and version 1.2 of monocraft

![image](https://user-images.githubusercontent.com/1346667/189363056-5183f4d3-81cb-4c82-bac2-dc9329c4917b.png)

**Comment by MAXOUXAX** [comment]
I can confirm that I have the same bug in all JetBrains software, including IntelliJ, but no problem in VSCode.
Also, all ligatures do it, not just `->`.
![image](https://user-images.githubusercontent.com/24844231/189839601-cabb37ef-9fa5-4fd4-97d9-ea8d89066f75.png)

**Comment by Xaeroxe** [comment]
ligatures are disabled by default in intellij products. Make sure to turn them on.

**Comment by caxapexac** [comment]
Clion 2022, confirm the bug

![image](https://user-images.githubusercontent.com/33996246/190638655-a0f4534c-8901-463c-8e85-96e36cf4de72.png)

**Comment by v36u** [comment]
This bug can be reproduced in `Rider 2022.2.3` too

![image](https://user-images.githubusercontent.com/61616221/191973167-1cff35ab-f5cd-4e89-a2c8-ff71a476e4b5.png)

**Comment by Giuliopime** [comment]
Getting the same issue in both IntelliJ and CLion

**Comment by IdreesInc** [comment]
Any chance someone could attempt to reproduce this with Monocraft v2.0? Not seeing it in my IntelliJ IDEA on MacOS

**Comment by proteck** [comment]
> Any chance someone could attempt to reproduce this with Monocraft v2.0? Not seeing it in my IntelliJ IDEA on MacOS

The problem is fix for me. Perfect 👌

**Comment by v36u** [comment]
I can no longer reproduce this. Tested in IntelliJ IDEA 2022.2.3 on Windows 10.

**Comment by IdreesInc** [comment]
Awesome, glad to hear it
