### ISSUE TITLE
Italics issues

### ISSUE THREAD

**Issue by gorbit99** [IdreesInc/Monocraft#32]
There are some issues when the characters are italicized (at least in the windows terminal)

First, some characters are cut off at the edge:
![image](https://user-images.githubusercontent.com/5338164/189347588-d7c90eef-302a-4657-b054-a069d47a5304.png)

Also, some characters shouldn't actually be italicized even if everything else is, for example pipe characters:
![image](https://user-images.githubusercontent.com/5338164/189347795-1a587545-0650-4e9f-9eb3-ee827acd6cb4.png)

Probably the same should apply to ligatures, as they aren't the best like that:
![image](https://user-images.githubusercontent.com/5338164/189347955-8a1866ab-2f20-4cae-844b-7f69ee7d7ade.png)

**Comment by IdreesInc** [comment]
Could someone with a Windows computer handy check and see if this is still the case with Monocraft 2.0?

**Comment by FroggyPanda** [comment]
> Could someone with a Windows computer handy check and see if this is still the case with Monocraft 2.0?

It doesn't seem to be an issue anymore. Tried my best to replicate whats in the images
![image](https://user-images.githubusercontent.com/101910741/210397214-12053de7-9e30-4ae9-8aa4-79e2770dc2a4.png)

**Comment by IdreesInc** [comment]
Possibly fixed with the new font weights/styles by @Dheatly23, but feel free to reopen this if it isn't!
