### ISSUE TITLE
Weird spacing in letter 'k'

### ISSUE THREAD

**Issue by WexCore** [IdreesInc/Monocraft#43]
Lowercase letter 'k' has extra "pixel" of space on the left, making it different from other "wide" letters. 
It bugs me a little. Is it considered intentional?
Maybe it would look better with a single extra pixel?

![eng_k_example](https://user-images.githubusercontent.com/19491308/189537968-32100efa-c662-4fce-9d52-e975d95f1aa7.png)

**Comment by IdreesInc** [comment]
It is intentional as it was meant to replicate the original Minecraft font, but I see what you mean. I'll play around with it a bit sometime this week and see what other bitmap fonts do with "k".

**Comment by IdreesInc** [comment]
Looks like there isn't really any good solution to this. Modifying the k to be wider looks a bit odd, but so does the spacing when next to another thin character like i. Might revisit in the future, but closing for now.

**Comment by IdreesInc** [comment]
Actually scratch that, was able to improve spacing of letters like "k" and "i" in #94
