### ISSUE TITLE
Missing Czech characters

### ISSUE THREAD

**Issue by Akxe** [IdreesInc/Monocraft#44]
Hi, I would love to use this, but since in my codebase we do have some Czech texts, it looks way off. 

I heard it is possible to add all variants via marks and glyphs, but since it was my first try, it was futile. But, I would consider donating some coins if the support for Czech language would be added :)

**Comment by T0biasCZe** [comment]
hotovo :) @Akxe 
![obrazek](https://user-images.githubusercontent.com/44525446/198020446-e8be1bf9-9b6a-4d8b-bb90-a9d5f5693641.png)

[Monocraft.zip](https://github.com/IdreesInc/Monocraft/files/9869182/Monocraft.zip)

**Comment by Akxe** [comment]
I do think that the line-height is too low. The `ů` is missing the top part.

**Comment by T0biasCZe** [comment]
its just windows installer not rendering it correctly, in software it shows correctly

**Comment by IdreesInc** [comment]
I believe I have added all characters in the Czech language as listed [here](https://en.wikipedia.org/wiki/Czech_orthography), but please let me know if I'm missing anything!

**Comment by Akxe** [comment]
@IdreesInc I saw the newly generated files, and they are great. They do have two characters, wrong thought... (more in bug report)
https://github.com/IdreesInc/Monocraft/issues/90
