### ISSUE TITLE
Include some more unicode symbols sometimes used in coding

### ISSUE THREAD

**Issue by artemisSystem** [IdreesInc/Monocraft#49]
Purescript has support for the following unicode symbols as part of its syntax:
`∀ ∷ → ← ⇒ ⇐`
Would be cool to see them included. I would contribute them myself, but i couldn't figure out how to add glyphs in fontforge

**Comment by IdreesInc** [comment]
For the arrows, we already have ligatures for `->`, `=>`, etc. Are these different from the ones you've suggested?

**Comment by artemisSystem** [comment]
Yes, i'm talking about actual different symbols, not ligatures

**Comment by IdreesInc** [comment]
Symbols have been added, will be released as part of v2.1 later tonight!
