### ISSUE TITLE
Cyrillic glyphs broken

### ISSUE THREAD

**Issue by Scratchbin** [IdreesInc/Monocraft#50]
![image](https://user-images.githubusercontent.com/29145652/191179599-028d0c18-4071-4c2c-ab04-efcff07db3cd.png)

**Comment by IdreesInc** [comment]
That's odd, do they appear broken when typed?

**Comment by IdreesInc** [comment]
Fixed as of https://github.com/IdreesInc/Monocraft/pull/74
