### ISSUE TITLE
Can the font be configured to work in Powershell/Windows Console?

### ISSUE THREAD

**Issue by minermaniac447** [IdreesInc/Monocraft#53]
I was trying to set the font as my PowerShell default font, but wasn't getting it to show up in the menu. I looked into it, and found that in order to show up in that menu, a font must fulfill these criteria (source: https://superuser.com/a/1381619):
- The font must be a fixed-pitch font.
- The font cannot be an italic font.
- If it is a TrueType font, it must be FF_MODERN.
- If it is not a TrueType font, it must contain the OEM_CHARSET.
- The font cannot have a negative A or C space.

Now, I'm not sure how much of this is something that needs to be changed (And I'm not sure how it would work with ligatures and other QOL things with the font), but would it be possible to either have a version of the font that had these configurations or have the base version of the font be configured this way?

**Comment by PRO-2684** [comment]
You may set any font as default if you use [windows terminal](https://www.microsoft.com/store/productId/9N0DX20HK701) as the console application.
![image](https://user-images.githubusercontent.com/54608551/195879574-e88f6cb4-ca7e-4b73-bca8-ae874ae45e1b.png)

**Comment by IdreesInc** [comment]
You can try using the new version 2.0 with PowerShell, but I doubt it will work. For now, it is recommended that you use Monocraft with Windows Terminal instead.
