### ISSUE TITLE
Linux Version

### ISSUE THREAD

**Issue by LinuxGamer** [IdreesInc/Monocraft#54]
Could you make a Linux version pls, I love the look of this and am only on Linux. would be awesome if you could :)

**Comment by nmarks413** [comment]
https://askubuntu.com/questions/18357/how-to-install-otf-fonts
use this guide to install an otf font on linux

**Comment by LinuxGamer** [comment]
> https://askubuntu.com/questions/18357/how-to-install-otf-fonts
> use this guide to install an otf font on linux

Thanks 🙏
