### ISSUE TITLE
Without Ligatures 

### ISSUE THREAD

**Issue by darkkivity** [IdreesInc/Monocraft#62]
Hello,

can you also provide a version without Ligatures?

**Comment by justsenne** [comment]
I can disable the ligatures in rider, so I think this is already optional

**Comment by IdreesInc** [comment]
As @justsenne mentioned, usually the software displaying ligatures has the option to disable them. Are you using a program that doesn't allow for that?

**Comment by darkkivity** [comment]
You can't turn ligature off in eclipse unfortunately. But I made a version without them.
[Monocraft.zip](https://github.com/IdreesInc/Monocraft/files/10227018/Monocraft.zip)

**Comment by IdreesInc** [comment]
Duplicate of https://github.com/IdreesInc/Monocraft/issues/10, version without ligatures will be released sometime tonight with v2.1
