### ISSUE TITLE
MS VSCode not recognizing the font family

### ISSUE THREAD

**Issue by sparty182020** [IdreesInc/Monocraft#63]
I have installed the font family, tried many different ways of putting the word Monocraft into the font family settings, I've opened up the WinOS settings and checked there (it was properly installed), but nothing works...

Font Version Installed: `001.400`

Visual Studio Code Install information:

![image](https://user-images.githubusercontent.com/69769526/202927284-dba2c5c8-7fd2-4022-94d5-d60014962b7b.png)

If you need anymore details, please PING me along with the information (pings will alert me sooner as I have a bot that texts me once I get pinged)

**Comment by mattcroat** [comment]
I had the same problem and solved it by [converting](https://cloudconvert.com/) the **.otf** file to **.ttf**.
