### ISSUE TITLE
Support for Latvian

### ISSUE THREAD

**Issue by NikitaKaj** [IdreesInc/Monocraft#64]
It'd be nice to include Latvian 😎 letters in the next version. Thank you for your work! ❤️

**Comment by Emilllo** [comment]
WE NEED LATVIAN!!!

**Comment by IdreesInc** [comment]
Sure thing, let me know what letters are included in the Latvian alphabet and I (or someone else) can go about adding them in

**Comment by NikitaKaj** [comment]
Ā ā, Č č, Ē ē, Ģ ģ, Ī ī, Ķ ķ, Ļ ļ, Ņ ņ, Š š, Ū ū, Ž ž

Here is the children's alphabet for better understanding:

![image](https://user-images.githubusercontent.com/102430946/209709674-3f2bfb97-786c-428d-bc05-cca1fe7764d7.png)

**Comment by IdreesInc** [comment]
Thanks for the write-up, should be available once I release version v2.1 tonight!
