### ISSUE TITLE
Spaceship operator

### ISSUE THREAD

**Issue by sol-vin** [IdreesInc/Monocraft#65]
The spaceship operator `<=>` is broken because of the confusion of `<=` and `<=>`.
![spaceshi](https://user-images.githubusercontent.com/1298501/206978847-b88ac7db-5d58-47a0-8623-55bb8c10d9c2.PNG)

**Comment by IdreesInc** [comment]
Will try to take a crack at it this weekend, thanks for the heads up!

**Comment by IdreesInc** [comment]
Complete as of https://github.com/IdreesInc/Monocraft/pull/74
