### ISSUE TITLE
How do I download a Chromebook or/and Chrome OS?

### ISSUE THREAD

**Issue by Minitoons123** [IdreesInc/Monocraft#69]

**Comment by Ciubix8513** [comment]
I think it's the same way as on Linux, see the readme for Linux installation instructions.

**Comment by IdreesInc** [comment]
Googled it a bit, looks like this would require putting the Chromebook into a developer mode of some sort which is probably not something I want to recommend to users unless they know what they're doing. Sorry I can't help you more!
