### ISSUE TITLE
Better distinguishment between parentheses and curly brackets

### ISSUE THREAD

**Issue by ftvkyo** [IdreesInc/Monocraft#7]
The `( )` look too similar to `{ }`. As this is a monospace font, it is likely to be used for programming, so their similarities will create difficulties for reading.

Moreover, here https://github.com/IdreesInc/Monocraft/blob/a4b13ab965d6a6f7a9b96278f290d25570408d2d/images/glyphs.png
the parentheses actually look exactly identical to the curly braces, unlike in the code example provided. This is probably not intentional.

**Comment by IdreesInc** [comment]
Braces have now been updated! Check the releases tab to download the newest version.
