### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by TechnologyClassroom** [IdreesInc/Monocraft#8]
I see you have no LICENSE file for this project.  The default is copyright.

I would suggest releasing the code under the CC-0, CC-BY, or MIT license so that others are able to modify and use your project within other projects.

**Comment by IdreesInc** [comment]
Thanks for the reminder! The font is now licensed as [SIL Open Font License 1.1](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL#9ccf5052)
