### ISSUE TITLE
A small break between pixels

### ISSUE THREAD

**Issue by Ciubix8513** [IdreesInc/Monocraft#88]
Small breaks in pixels sometimes appear:
![image](https://user-images.githubusercontent.com/57328501/209925941-9e4b480b-7934-4a69-abe7-ff083bd32f19.png)
 
![image](https://user-images.githubusercontent.com/57328501/209925967-5be425ce-a080-4d31-9dfc-e0cd5ba974e9.png)
This glitch occurs with both the ttf and otf version, but it's more severe in the ttf

Haven't tested it on other platforms, but I am using Linux, X11 and gnome specifically with proprietary NVIDIA drivers

**Comment by azeine** [comment]
Can confirm the glitch, but it only occurs in the otf version of the font.
My platform is Windows 11, and AMD Integrated graphics, and my screen resolution is 1366x768

.otf :
![image](https://user-images.githubusercontent.com/95456933/210234574-011d7d13-4f06-4e37-9fd2-6db60cdfd116.png)

.ttf :
![image](https://user-images.githubusercontent.com/95456933/210234630-8aa4e469-8806-4215-b2a4-69ebe4fb1419.png)

**Comment by Flyingbacen** [comment]
I haven't looked at the otf file, but on Linux Mint, the ttf file does have a break too, except it's with all letters.
![image](https://user-images.githubusercontent.com/73092546/210908419-6842f182-092b-4a72-a53f-4a692132d947.png)

**Comment by radaelilucca** [comment]
It's happening algo on Pop-os 22.04 and can be fixed using different font sizes: 
![image](https://user-images.githubusercontent.com/29178479/211378648-d0582d85-c1e9-417e-95bc-0fe771820e17.png)
