### ISSUE TITLE
Add a .ttf file version for use with OLED displays

### ISSUE THREAD

**Issue by BashPink** [IdreesInc/Monocraft#9]
I stumbled across your repo on Reddit and would LOVE to use this with a personal project. The SSD1306 driver uses .ttf files and cannot read .oft files. I would love to see that if possible.

**Comment by timpickles** [comment]
Until the `.ttf` is added to the repo I believe you should be able to create your own by installing [Fontforge](https://fontforge.org/en-US/) and opening the `fontforge/Monocraft.sfd` file and saving as `.ttf`.

It may also be possible to do this on the command line with the following:
```
fontforge -lang=ff -c 'Open($1); Generate($2); Close();' Monocraft.otf Monocraft.ttf
```

**Comment by mainrs** [comment]
A GitHub CI workflow would probably be a good idea. That way, a new tag could build both versions of the font and attach the files to a release.

**Comment by IdreesInc** [comment]
100% agree with the workflow suggestion, or at least automating things like this in some way. I'm going to need to look into whether I can make scripts for things like this, otherwise each new addition to the font will become tedious,

**Comment by IdreesInc** [comment]
Complete as part of https://github.com/IdreesInc/Monocraft/pull/74, check out the releases page for the `.ttf` and `.otf` versions
