### ISSUE TITLE
Aphostrope on some letters are wrong

### ISSUE THREAD

**Issue by Akxe** [IdreesInc/Monocraft#90]
**Describe the bug**
The letters `ťď` are wrong

**Expected behavior**
The `ˇ` symbol should not be added to small `d` and `t`, they do receive special version of it.

**Screenshots**
![image](https://user-images.githubusercontent.com/2001798/209984042-a82f1c79-71e6-4e60-9e9f-4abbe43f7817.png)

**Operating system**
Windows

**Software**
Windows and all others

**Additional context**

**Comment by IdreesInc** [comment]
Thanks for catching that, fixed!
